adult_words = [
                  "ability", "accident", "account", "action", "activity", "addition", "address", "advantage",
                  "afternoon", "agent", "agreement", "airline", "airport", "alarm", "alcohol", "ambition", "American",
                  "analysis", "analyst", "anger", "angle", "animal", "anxiety", "apartment", "appeal", "appearance",
                  "argument", "arrival", "article", "aside", "assignment", "assist", "assistance", "assistant",
                  "associate", "assumption", "atmosphere", "attempt", "attention", "attitude", "audience", "author",
                  "average", "award", "awareness", "background", "balance", "baseball", "bathroom", "battle", "beach",
                  "bedroom", "bench", "benefit", "bicycle", "birthday", "bitter", "black", "blame", "blank", "blind",
                  "block", "border", "bother", "bottle", "bottom", "bowl", "boyfriend", "brain", "branch", "breakfast",
                  "breast", "brick", "bridge", "brother", "brush", "buddy", "budget", "bunch", "business", "button",
                  "cabinet", "cable", "cake", "calendar", "campaign", "candidate", "candle", "candy", "capital", "car",
                  "career", "carpet", "carry", "catch", "category", "chain", "chair", "challenge", "champion",
                  "channel", "chapter", "character", "charity", "chart", "chemistry", "chicken", "childhood",
                  "chocolate", "choice", "cigarette", "classroom", "clerk", "click", "climate", "clock", "closet",
                  "clothes", "cloud", "coach", "collar", "collection", "college", "comfort", "comment", "commission",
                  "committee", "community", "company", "comparison", "complaint", "computer", "concept", "concert",
                  "conclusion", "condition", "conference", "confidence", "confusion", "connection", "contact",
                  "contest", "context", "contract", "control", "cooing", "corner", "counter", "country", "couple",
                  "courage", "court", "Cowardly", "Crabby", "crack", "cream", "credit", "criticism", "cross", "culture",
                  "currency", "curve", "customer", "cycle", "damage", "daring", "database", "daughter", "deafening",
                  "debate", "decision", "defeated", "definition", "degree", "delicious", "delightful", "delivery",
                  "department", "departure", "depression", "designer", "desire", "detail", "devil", "diamond",
                  "difference", "Difficult", "difficulty", "dimension", "direction", "director", "disaster",
                  "discipline", "discount", "discussion", "disease", "distance", "district", "doctor", "document",
                  "draft", "drawing", "dream", "dress", "economics", "economy", "education", "effect", "efficiency",
                  "election", "elegant", "elevator", "emergency", "emotion", "emphasis", "employee", "employer",
                  "employment", "endless", "engineer", "enthusiasm", "entrance", "equipment", "essay", "evening",
                  "evidence", "exchange", "Excited", "excitement", "exhausted", "expert", "expression", "extension",
                  "factor", "failure", "famous", "fantastic", "farm", "father", "fault", "feedback", "feeling",
                  "fierce", "fight", "filthy", "finance", "finding", "finger", "fishing", "floor", "flower", "fluffy",
                  "Fluttering", "foolish", "football", "fortune", "foundation", "frame", "freedom", "French", "friend",
                  "friendship", "frightened", "front", "fruit", "function", "funeral", "furious", "future", "garage",
                  "garbage", "gentle", "gifted", "girlfriend", "glamorous", "Glassy", "Gloomy", "glove", "Glowing",
                  "government", "grade", "grass", "grocery", "ground", "guarantee", "guidance", "habit", "hearing",
                  "highlight", "highway", "historian", "history", "holiday", "hollow", "homework", "horror", "horse",
                  "hospital", "housing", "husband", "impact", "implement", "importance", "impression", "incident",
                  "indication", "industry", "inflation", "influence", "initiative", "inspection", "inspector",
                  "instance", "insurance", "intention", "internet", "interview", "investment", "island", "issue",
                  "jacket", "joint", "judge", "judgment", "juice", "kitchen", "knife", "knowledge", "land", "landscape",
                  "language", "lawyer", "layer", "leadership", "league", "leather", "lecture", "lesson", "letter",
                  "library", "likely", "limit", "literature", "little", "location", "lock", "luck", "lunch", "machine",
                  "magazine", "management", "manager", "manner", "marketing", "marriage", "master", "match", "material",
                  "maximum", "meaning", "medicine", "meeting", "melodic", "melted", "membership", "message", "metal",
                  "midnight", "minimum", "minute", "mirror", "mission", "mistake", "mixture", "monitor", "morning",
                  "mortgage", "motor", "mountain", "mouth", "muscle", "nail", "narrow", "nerve", "nervous", "network",
                  "newspaper", "noise", "notice", "novel", "nurse", "obligation", "occasion", "officer", "opening",
                  "operation", "opinion", "option", "orange", "outcome", "package", "paint", "painting", "panic",
                  "panicky", "parent", "park", "parking", "partner", "party", "passage", "passenger", "passion",
                  "patience", "patient", "pattern", "pause", "payment", "peace", "penalty", "pension", "percentage",
                  "perception", "period", "permission", "phase", "philosophy", "phrase", "physics", "plane", "plant",
                  "plastic", "plate", "platform", "pleasure", "polite", "politics", "pollution", "population",
                  "position", "possession", "pound", "preference", "presence", "president", "pressure", "prickly",
                  "pride", "priest", "principle", "priority", "prize", "problem", "procedure", "product", "profession",
                  "professor", "profile", "program", "progress", "project", "promise", "promotion", "proof", "property",
                  "proposal", "protection", "psychology", "quality", "quantity", "quantity", "quarter", "question",
                  "reaction", "reading", "reality", "reason", "reception", "record", "recording", "reference",
                  "reflection", "register", "relation", "relative", "relief", "republic", "repulsive", "reputation",
                  "request", "resident", "resolution", "resort", "resource", "respect", "response", "restaurant",
                  "revenue", "review", "revolution", "reward", "rotten", "routine", "salary", "sand", "sandwich",
                  "savings", "Scared", "schedule", "scheme", "science", "score", "screen", "screw", "script", "season",
                  "secretary", "security", "selection", "sentence", "session", "setting", "shame", "shape", "share",
                  "shelter", "shock", "shopping", "shoulder", "shower", "Shrill", "signal", "signature", "situation",
                  "skirt", "slice", "Smelly", "smoke", "Soaring", "society", "software", "solution", "speaker",
                  "specialist", "spirit", "spite", "spray", "square", "stable", "staff", "stage", "standard",
                  "statement", "station", "status", "stick", "stomach", "storage", "storm", "straight", "stranger",
                  "strategy", "street", "strength", "stress", "string", "stroke", "strong", "structure", "stubborn",
                  "student", "stuff", "subject", "substance", "success", "sugar", "suggestion", "summer", "surgery",
                  "surprise", "swimming", "switch", "sympathy", "table", "tackle", "target", "taste", "teacher",
                  "teaching", "technology", "telephone", "television", "tension", "theme", "thought", "ticket", "title",
                  "tourist", "towel", "tower", "track", "tradition", "traffic", "trainer", "training", "transition",
                  "trash", "tree", "triangular", "trick", "tricky", "trouble", "truck", "trust", "university",
                  "unsightly", "vacation", "variation", "variety", "vegetable", "vehicle", "version", "village",
                  "voice", "warning", "weakness", "Weather", "wedding", "weekend", "weight", "welcome", "wheel",
                  "window", "winter", "witness", "wooden", "worried", "writing", "Year 4 – 6"
              ],
[
    "representative", "international", "professional", "alternative", "comfortable", "independent", "commercial",
    "equivalent", "individual", "inevitable", "particular", "brilliant", "dependent", "effective", "necessary",
    "objective", "potential", "sensitive", "spiritual", "temporary", "beautiful", "somewhere", "yesterday", "chemical",
    "constant", "creative", "external", "familiar", "internal", "national", "official", "ordinary", "original",
    "personal", "physical", "positive", "possible", "specific", "upstairs", "valuable", "negative", "opposite",
    "anywhere", "tomorrow", "classic", "current", "extreme", "general", "illegal", "leading", "primary", "private",
    "regular", "special", "western", "working", "natural", "complex", "initial", "present", "tonight", "forever",
    "active", "annual", "common", "female", "junior", "middle", "mobile", "normal", "public", "remote", "secret",
    "senior", "simple", "stupid", "unique", "visual", "formal", "double", "single", "yellow", " crispy", "absurd",
    "abundant", "Afraid", "agreeable", "amusing", "ancient", "apologetic", "Australian", "bashful", "Beautiful",
    "better", "bewildered", "bitter", "boiling", "breeze", "brilliant", "broken", "capable", "Carefree", "careful",
    "Careless", "Caring", "cautious", "charming", "cheerful", "chilly", "chilly", "chubby", "clever", "cloudy",
    "clumsy", "colossal", "cranky", "Crawling", "Creaky", "creative", "Creeping", "creepy", "crispy", "crooked",
    "cuddly", "curved", "damaged", "dangerous", "delicate", "dreadful", "ecstatic", "enormous", "faithful", "freezing",
    "friendly", "Generous", "gigantic", "glass", "gorgeous", "graceful", "greasy", "Greedy", "grumpy", "handsome",
    "helpful", "helpless", "Hideous", "hissing", "honest", "Hopeful", "Horrid", "ideal", "immense", "important",
    "infinite", "innocent", "Japanese", "jealous", "Jewish", "joyful", "kind", "kindly", "lively", "living", "Lutheran",
    "mammoth", "marvellous", "marvelous", "massive", "medium", "Mighty", "miniature", "modern", "Muffled", "mysterious",
    "native", "naughty", "nimble", "north", "numerous", "nutritious", "obedient", "obnoxious", "optimistic", "petite",
    "pleasant", "plenty", "powerful", "precise", "pretty", "purple", "purple", "purring", "quaint", "relieved",
    "scrawny", "screeching", "Selfish", "shallow", "Shining", "shocking", "silver", "simple", "Sizzling", "skinny",
    "Sleepy", "slippery", "sloppy", "smooth", "south", "sparkling", "sparse", "Speedy", "Splendid", "spoiled",
    "Starving", "Steaming", "sticky", "Stingy", "stinky", "Strict", "Stuffed", "stunning", "Sturdy", "Surprised",
    "swollen", "tasteless", "teeny-tiny", "temporary", "tender", "terrified", "textures", "thankful", "Thrifty",
    "thundering", "truthful", "ugliest", "uptight", "victorious", "voiceless", "whimsical", "whispering", "wide-eyed",
    "Wonderful", "Wrinkly", "yellow", "zealous", "uneven"
]
]



child_words = [
[
    "actor", "advice", "apple", "basket", "bird", "bonus", "breath", "camera", "cookie", "dinner", "drawer", "energy",
    "farmer", "flight", "food", "guitar", "idea", "insect", "ladder", "leader", "movie", "music", "number", "office",
    "oven", "paper", "phone", "piano", "pizza", "place", "point", "potato", "river", "salad", "school", "series",
    "singer", "speech", "story", "tennis", "thing", "truth", "video", "volume", "water", "winner", "world", "writer",
    "youth"
],
[
    "adult", "alert", "angry", "aware", "big", "blue", "Bored", "brave", "brief", "broad", "brown", "busy", "calm",
    "clear", "cold", "cool", "cozy", "crazy", "curly", "drunk", "dusty", "eager", "early", "easy", "equal", "Fair",
    "fancy", "fast", "few", "final", "fresh", "funny", "glad", "good", "grand", "great", "green", "happy", "Hasty",
    "heavy", "high", "human", "icy", "jumpy", "kind", "late", "local", "long", "low", "loyal", "lucky", "main", "major",
    "many", "maybe", "minor", "most", "nasty", "new", "nice", "odd", "one", "other", "past", "pink", "prior", "proud",
    "quick", "quiet", "rainy", "rough", "round", "royal", "Rusty", "silly", "solid", "spare", "spiky", "still", "sunny",
    "sweet", "swift", "tall", "today", "total", "tough", "upper", "usual", "weird", "white", "whole", "Wild", "windy",
    "wise", "witty", "worth", "young"
]
]
